//
// ApiSecuritySignUpRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiSecuritySignUpRequest: Codable, JSONEncodable, Hashable {

    public var username: String?
    public var password: String
    public var email: String?
    public var secret: String

    public init(username: String? = nil, password: String, email: String? = nil, secret: String) {
        self.username = username
        self.password = password
        self.email = email
        self.secret = secret
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
        case email
        case secret
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encode(password, forKey: .password)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encode(secret, forKey: .secret)
    }
}

