//
// ApiSecuritySignInRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiSecuritySignInRequest: Codable, JSONEncodable, Hashable {

    public var username: String?
    public var password: String

    public init(username: String? = nil, password: String) {
        self.username = username
        self.password = password
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encode(password, forKey: .password)
    }
}

