//
// CatRandom200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CatRandom200Response: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var mimetype: String?
    public var size: Double?
    public var tags: [String]

    public init(id: String? = nil, mimetype: String? = nil, size: Double? = nil, tags: [String]) {
        self.id = id
        self.mimetype = mimetype
        self.size = size
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case mimetype
        case size
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(mimetype, forKey: .mimetype)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encode(tags, forKey: .tags)
    }
}

